apiVersion: v1
kind: Pod
metadata:
  name: exm2-server-high-1
  labels:
    app: iperf
spec:
  nodeSelector:
    kubernetes.io/hostname: hygon1
  containers:
    # 第一个 iperf3 server: 监听 5201
    - name: iperf-5201
      image: ubuntu-net:latest
      imagePullPolicy: IfNotPresent
      command: ["iperf3", "-s", "-p", "5201"]
      ports:
        - containerPort: 5201
          name: port5201
---
apiVersion: v1
kind: Pod
metadata:
  name: exm2-server-high-2
  labels:
    app: iperf
spec:
  nodeSelector:
    kubernetes.io/hostname: hygon1
  containers:
    - name: iperf-5201
      image: ubuntu-net:latest
      imagePullPolicy: IfNotPresent
      command: ["iperf3", "-s", "-p", "5201"]
      ports:
        - containerPort: 5201
          name: port5201
---
apiVersion: v1
kind: Pod
metadata:
  name: exm2-server-low
  labels:
    app: iperf
  annotations:
    kubernetes.io/egress-bandwidth: "400M"
    kubernetes.io/ingress-bandwidth: "400M"
spec:
  nodeSelector:
    kubernetes.io/hostname: hygon1
  containers:
  - name: iperf
    image: ubuntu-net:latest
    imagePullPolicy: IfNotPresent
    command: ["iperf3", "-s", "-p", "5201"]
    ports:
    - containerPort: 5201    # 显式声明监听端口
