apiVersion: v1
kind: Pod
metadata:
  name: server-1
  labels:
    app: sockperf
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.255.24.11\"]"
spec:
  restartPolicy: Never
  nodeName: sdu-super-server
  containers:
    - name: sockperf
      image: ubuntu-net:latest
      imagePullPolicy: IfNotPresent
      command: ["sockperf", "sr", "--tcp", "-p", "5201"]
      ports:
        - containerPort: 5201
          name: port5201

---
apiVersion: v1
kind: Pod
metadata:
  name: server-2
  labels:
    app: sockperf
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.255.24.12\"]"
spec:
  restartPolicy: Never
  nodeName: sdu-super-server
  containers:
    - name: sockperf
      image: ubuntu-net:latest
      imagePullPolicy: IfNotPresent
      command: ["sockperf", "sr", "--tcp", "-p", "5201"]
      ports:
        - containerPort: 5201
          name: port5201
---
apiVersion: v1
kind: Pod
metadata:
  name: server-3
  labels:
    app: sockperf
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.255.24.13\"]"
spec:
  restartPolicy: Never
  nodeName: sdu-super-server
  containers:
    - name: sockperf
      image: ubuntu-net:latest
      imagePullPolicy: IfNotPresent
      command: ["sockperf", "sr", "--tcp", "-p", "5201"]
      ports:
        - containerPort: 5201
          name: port5201
