worker_processes auto;

events {
    worker_connections 4096;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;
    types_hash_max_size 4096;

    # 调优: 大文件/高并发优化
    aio             on;
    directio        512;
    output_buffers  1 512k;
    sendfile_max_chunk 512k;

    server {
        listen 80;
        server_name _;

        # DASH 文件路径（PVC 挂载到 /var/www/html）
        root /var/www/html;

        index index.html;

        location / {
            autoindex on;      # 可以直接浏览文件目录
            try_files $uri $uri/ =404;
        }
    }
}
