apiVersion: v1
kind: Pod
metadata:
  name: exm6-file-server
  labels:
    app: iperf
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.255.24.4\"]"
    oncn-bwm.openeuler.org/egress-bandwidth: '{"request":"10","limit":"1000","priority":"0"}'
    oncn-bwm.openeuler.org/ingress-bandwidth: '{"request":"10","limit":"1000","priority":"0"}'
spec:
  nodeSelector:
    kubernetes.io/hostname: hygon1
  containers:
    - name: iperf-5201
      image: ubuntu-net:latest
      imagePullPolicy: IfNotPresent
      command: ["iperf3", "-s", "-p", "5201"]
      # command: ["sockperf", "server", "-p", "5201", "--tcp"]
      ports:
        - containerPort: 5201
          name: port5201
